=== Nasreen027/xml/external.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT company (employe*, (client | user))>
<!ELEMENT employe (name,(email | number), password)>
<!ELEMENT client (name,email,password)>
<!ELEMENT user (name, email, password)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT number (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ATTLIST name profile CDATA #REQUIRED>

=== Nasreen027/xml/file.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE company SYSTEM "external.dtd"[
<!ENTITY ps "pass112">
]>
<company>
    <employe>
        <name profile="Frontend Developer">Ali</name>
        <email>ali@gmail.com</email>
        <password>12345</password>
    </employe>
    <client>
        <name profile="Web Designer">Asim</name>
        <email>asim@gmail.com</email>
        <password>&ps;</password>
    </client>
</company>
